# version
version: '3'

# services
services:
  yolo:
    build: ./yolo
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: /app.py
    ports:
      - '5000-5002:5000'

  frontend:
    build: ./frontend
    ports:
      - 80:80
